language: ruby
stack: docker
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_FREE_MIN=200000
# services:
#   - redis
addons:
  postgresql: 9.3
rvm:
  - 2.1.0
before_script:
  - sudo service mysql stop
  - redis-server /etc/redis/redis.conf
  - redis-cli config set save ""
  - 'RAILS_ENV=test rake db:create db:structure:load --trace'
script:
  - './build.sh'
notifications:
  email: false
